### ISSUE TITLE
can't import product

### ISSUE THREAD

**Issue by 99cm** [autotelik/datashift_spree#48]
I did generate spree product template and export spree product. But could not import spree product.
I used this command line:
bundle exec thor datashift:import:excel -i --input=spree_product.xls -m --model=Spree::Product -a

response is No value provided for option '--input'
![datashiftclip1](https://cloud.githubusercontent.com/assets/14033183/10126106/bf237e7c-6558-11e5-9fed-5d5c1ddbb510.jpg)

**Comment by autotelik** [comment]
thor options are shown in short form/long form .. you have used BOTH -i and --input .. you only need one of them

**Comment by autotelik** [comment]
same for the others  either  -m   or --model not both

**Comment by 99cm** [comment]
I tried 1 row data, but failed.
Report summary as follows:
Processing Column 0
Current value to assign : Huan Lian Su Coated Tablets
Failed to process row [1]
["C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/datashift-0.15.0/lib/datashift/populator.rb:125:in `assign'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/datashift-0.15.0/lib/loaders/loader_base.rb:342:in `process'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/datashift-0.15.0/lib/loaders/excel_loader.rb:125:in `block (3 levels) in perform_excel_load'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/datashift-0.15.0/lib/loaders/excel_loader.rb:113:in `each'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/datashift-0.15.0/lib/loaders/excel_loader.rb:113:in `block (2 levels) in perform_excel_load'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/spreadsheet-1.0.5/lib/spreadsheet/worksheet.rb:147:in `block in each'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/spreadsheet-1.0.5/lib/spreadsheet/worksheet.rb:146:in `upto'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/spreadsheet-1.0.5/lib/spreadsheet/worksheet.rb:146:in `each'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/spreadsheet-1.0.5/lib/spreadsheet/excel/worksheet.rb:47:in `each'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/datashift-0.15.0/lib/loaders/excel_loader.rb:84:in `each_with_index'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/datashift-0.15.0/lib/loaders/excel_loader.rb:84:in `block in perform_excel_load'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/datashift-0.15.0/lib/loaders/excel_loader.rb:82:in `perform_excel_load'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/datashift-0.15.0/lib/loaders/excel_loader.rb:204:in `perform_load'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/datashift-0.15.0/lib/thor/import.thor:79:in `excel'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/runner.rb:36:in `method_missing'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.19.1/bin/thor:6:in `<top (required)>'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/bin/thor:23:in `load'", "C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/bin/thor:23:in `<main>'"]

**Comment by autotelik** [comment]
sorry this is an open source project, I do not have the time to provide support for individual  data issues. I would suggest you fork the project and try to debug the code. Could maybe be a data format issue, as something being thrown from the spreadsheet gem .... e.g  C:/inetpub/vhosts/99chinesemedicine.com/httpdocs/App_Data/Ruby22-x64/lib/ruby/gems/2.2.0/gems/spreadsheet-1.0.5/lib/spreadsheet/worksheet.rb
