### ISSUE TITLE
uninitialized constant DataShift::CsvLoading (NameError)

### ISSUE THREAD

**Issue by nischay-webonise** [autotelik/datashift_spree#63]
gems/datashift_spree-0.5.0/lib/loaders/spree/spree_base_loader.rb:19:in `<class:SpreeBaseLoader>': uninitialized constant DataShift::CsvLoading (NameError)

Stack Trace -- 

from personal/.rvm/gems/ruby-2.3.0@project/gems/datashift_spree-0.5.0/lib/loaders/spree/spree_base_loader.rb:18:in `<module:DataShift>'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/datashift_spree-0.5.0/lib/loaders/spree/spree_base_loader.rb:16:in `<top (required)>'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/datashift_spree-0.5.0/lib/loaders/spree/product_loader.rb:8:in `<top (required)>'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/datashift_spree-0.5.0/lib/thor/spree/products_images.thor:42:in `products'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/thor-0.19.1/lib/thor/runner.rb:36:in `method_missing'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  from personal/.rvm/gems/ruby-2.3.0@project/gems/thor-0.19.1/bin/thor:6:in `<top (required)>'
  from personal/.rvm/gems/ruby-2.3.0@project/bin/thor:23:in `load'
  from personal/.rvm/gems/ruby-2.3.0@project/bin/thor:23:in `<main>'
  from personal/.rvm/gems/ruby-2.3.0@project/bin/ruby_executable_hooks:15:in `eval'
  from personal/.rvm/gems/ruby-2.3.0@project/bin/ruby_executable_hooks:15:in `<main>'

**Comment by myjonboy** [comment]
same error for DataShift::ExcelLoading

**Comment by autotelik** [comment]
I'm currently working on moving Spree to the latest datashift API here -  https://github.com/autotelik/datashift_spree/tree/feature/update_api_latest_ds_and_spree

But I don't actually work with Spree day to day now, so going slowly   - so in meantime you probably need to revert to previous versions prob Datashift version 0.16  ...  and 0. 5 for DS Spree

**Comment by APohio** [comment]
To anyone stumbling upon this when using 3-0 or above, this is what you need in your gemfile:

gem 'datashift', git: 'https://github.com/autotelik/datashift'
gem 'datashift_spree', git: 'https://github.com/autotelik/datashift_spree', :branch => 'feature/update_api_latest_ds_and_spree'
